version: "0.5"

processes:
  postgresql:
    command: "cd .devbox/virtenv/postgresql && pg_ctl start -o \"-k $PGHOST\""
    is_daemon: true
    shutdown:
      command: "cd .devbox/virtenv/postgresql && pg_ctl stop -m fast"
    availability:
      restart: "always"

  minio:
    command: "minio server temp/minio-data --console-address ':9001'"
    is_daemon: true
    shutdown:
      command: "pkill minio"
    availability:
      restart: "always"
